root = "."
tmp_dir = "dist"

[build]
  cmd = "go build -o ./dist/main ./src > /tmp/go-build.log 2>&1"
  bin = "./dist/main"
  full_bin = "APP_BINARY=./dist/main ./dist/main"
  include_ext = ["go"]
  include_dir = ["src"]
  exclude_dir = ["dist"]
  log = "air_errors.log"

[log]
  silent = false
  main_only = false
  time = false

[misc]
  clean_on_exit = true